let lastResults=[]; let favoriteIds=new Set();
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
async function api(url,opt){const r=await fetch(url,opt);if(!r.ok)throw new Error((await r.json()).error||'Request failed');return r.json()}
async function loadFavorites(){const f=await api('/api/favorites');favoriteIds=new Set(f.map(x=>x.id));renderFavorites(f)}
function renderResults(results){const box=$('#results');$('#resultCount').textContent=`找到 ${results.length} 筆結果`;if(!results.length){box.innerHTML='<div class="empty">找不到符合條件的資料。你可以換成零件型號或較短的關鍵字。</div>';return}box.innerHTML=results.map(r=>{const map=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(r.store.address||r.store.name)}`;return `<article class="card"><div class="cardTop"><div><h3>${esc(r.name)}</h3><div class="muted">${esc(r.partNumber)} · ${esc(r.spec)}</div></div><span class="pill unknown">尚未確認現貨</span></div><p class="muted">🏪 ${esc(r.store.name)} · ${esc(r.store.city)} ${esc(r.store.district||'')}</p><div class="price">${r.price==null?'價格待確認':'NT$ '+r.price}</div><p class="muted">資料最後檢查：${new Date(r.lastChecked).toLocaleString('zh-TW',{hour12:false})}</p><div class="actions"><button class="primary" onclick="inquire('${r.store.id}','${r.id}')">建立詢問</button><button onclick="toggleFav('${r.store.id}')">${favoriteIds.has(r.store.id)?'★ 已收藏':'☆ 收藏店家'}</button><a href="${map}" target="_blank" rel="noopener">地圖</a></div></article>`}).join('')}
async function search(){const q=$('#query').value.trim();const city=$('#city').value;const data=await api(`/api/search?q=${encodeURIComponent(q)}&city=${encodeURIComponent(city)}`);lastResults=data.results;sortResults()}
function sortResults(){let a=[...lastResults],v=$('#sort').value;if(v==='price')a.sort((x,y)=>(x.price??999999)-(y.price??999999));if(v==='name')a.sort((x,y)=>x.name.localeCompare(y.name));renderResults(a)}
async function toggleFav(id){if(favoriteIds.has(id)){await api('/api/favorites/'+id,{method:'DELETE'});favoriteIds.delete(id);toast('已取消收藏')}else{await api('/api/favorites/'+id,{method:'POST'});favoriteIds.add(id);toast('已收藏店家')}renderResults(lastResults);loadFavorites()}
async function inquire(storeId,productId){const qty=prompt('要詢問幾個？','1');if(qty===null)return;const note=prompt('備註（可留空）：','');await api('/api/inquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({storeId,productId,quantity:qty,note})});toast('已建立詢問紀錄');loadInquiries()}
function renderFavorites(stores){const box=$('#favorites');if(!stores.length){box.innerHTML='<div class="empty">還沒有收藏店家。</div>';return}box.innerHTML=stores.map(s=>`<article class="card"><h3>${esc(s.name)}</h3><p class="muted">${esc(s.city)} · ${esc(s.district||'')}<br>${esc(s.address||'')}</p><div class="actions"><a href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.address||s.name)}" target="_blank">地圖</a><button onclick="toggleFav('${s.id}')">取消收藏</button></div></article>`).join('')}
async function loadInquiries(){const rows=await api('/api/inquiries');const box=$('#inquiries');if(!rows.length){box.innerHTML='<div class="empty">還沒有詢問紀錄。</div>';return}box.innerHTML=rows.map(x=>`<div class="row"><div><b>${esc(x.productName)}</b><div class="muted">${esc(x.storeName)} · ${x.quantity} 個${x.note?' · '+esc(x.note):''}</div></div><span class="pill">${esc(x.status)}</span></div>`).join('')}
function switchPage(name){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$('#page-'+name).classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===name));if(name==='favorites')loadFavorites();if(name==='inquiries')loadInquiries()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>switchPage(b.dataset.page));$('#searchBtn').onclick=search;$('#sort').onchange=sortResults;$('#query').addEventListener('keydown',e=>{if(e.key==='Enter')search()});
search();loadFavorites();
